### PR TITLE
Login Page!

### PR DESCRIPTION
**Pull request by maharshmellow**
This PR adds the Login Page (doesn't touch the backend). It contains both the signup and signin fields. It checks the fields for errors and if there is an error, it will show a little red message. If everything is good, it sends the requests to the django auth registration and login endpoints. After a successful login, it just shows an alert with the message "Success" for now but this will be replaced with a redirection to the homepage. 

Enzyme + Jest is used for all the front-end tests so please make sure to read about those if you're not familiar. Also added bootstrap so we can make use of it's grid system for everything.

### CODE REVIEW

**Review by zhaoyuxuan — APPROVED** [review]
Looks good!

**Review by ceciliaccwei — APPROVED** [review]
Amazing!

**Comment by roychowd** [comment]
Nice!

**Review by roychowd — APPROVED** [review]
Nice

**Pull request merged**
